import requests
import pandas as pd
import ta


OKX_BASE_URL = "https://www.okx.com/api/v5/market/candles"

INTERVAL_MAP = {
    "1m": "1m",
    "3m": "3m",
    "5m": "5m",
    "15m": "15m",
    "30m": "30m",
    "1h": "1H",
    "2h": "2H",
    "4h": "4H",
    "6h": "6H",
    "12h": "12H",
    "1d": "1D",
}


def _okx_symbol(symbol: str) -> str:
    clean = symbol.upper().replace("/", "").replace("-", "")
    if clean.endswith("USDT"):
        return f"{clean[:-4]}-USDT-SWAP"
    return clean


def _get_candles(symbol: str, interval: str, limit: int = 300):
    inst_id = _okx_symbol(symbol)
    bar = INTERVAL_MAP.get(interval, "1H")

    params = {
        "instId": inst_id,
        "bar": bar,
        "limit": min(max(limit, 200), 300),
    }
    headers = {"User-Agent": "SmartOTC-AI/1.0"}

    try:
        response = requests.get(
            OKX_BASE_URL,
            params=params,
            headers=headers,
            timeout=15,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        return None, {"error": "OKX request failed", "details": str(exc)}

    try:
        payload = response.json()
    except ValueError:
        return None, {
            "error": "OKX returned non-JSON response",
            "status": response.status_code,
            "body": response.text[:500],
        }

    if payload.get("code") != "0":
        return None, {
            "error": "OKX API error",
            "code": payload.get("code"),
            "message": payload.get("msg", "Unknown OKX error"),
            "instrument": inst_id,
        }

    rows = payload.get("data") or []
    if not rows:
        return None, {
            "error": "No candle data returned by OKX",
            "instrument": inst_id,
            "interval": bar,
        }

    rows = list(reversed(rows))
    parsed = []
    for row in rows:
        if len(row) < 9:
            continue
        parsed.append({
            "time": int(row[0]),
            "open": float(row[1]),
            "high": float(row[2]),
            "low": float(row[3]),
            "close": float(row[4]),
            "volume": float(row[5]),
            "confirm": str(row[8]),
        })

    if len(parsed) < 200:
        return None, {
            "error": "Insufficient candle data",
            "received": len(parsed),
            "required": 200,
            "instrument": inst_id,
        }

    return parsed, None


def _indicator_frame(candles):
    df = pd.DataFrame(candles).copy()
    df["ema20"] = ta.trend.ema_indicator(df["close"], window=20)
    df["ema50"] = ta.trend.ema_indicator(df["close"], window=50)
    df["ema200"] = ta.trend.ema_indicator(df["close"], window=200)
    df["rsi"] = ta.momentum.rsi(df["close"], window=14)

    macd = ta.trend.MACD(
        df["close"], window_slow=26, window_fast=12, window_sign=9
    )
    df["macd"] = macd.macd()
    df["macd_signal"] = macd.macd_signal()
    df["atr"] = ta.volatility.average_true_range(
        df["high"], df["low"], df["close"], window=14
    )

    return df.dropna().reset_index(drop=True)


def _score_row(row, prev):
    score = 0

    bullish_trend = row["ema20"] > row["ema50"] > row["ema200"]
    bearish_trend = row["ema20"] < row["ema50"] < row["ema200"]

    if bullish_trend:
        score += 30
    elif bearish_trend:
        score -= 30

    if row["close"] > row["ema20"]:
        score += 10
    elif row["close"] < row["ema20"]:
        score -= 10

    if 52 <= row["rsi"] <= 68:
        score += 15
    elif 32 <= row["rsi"] < 48:
        score -= 15
    elif 68 < row["rsi"] <= 75:
        score += 5
    elif 25 <= row["rsi"] < 32:
        score += 5
    elif row["rsi"] > 75:
        score -= 15
    elif row["rsi"] < 25:
        score += 15

    macd_bull = row["macd"] > row["macd_signal"]
    macd_bear = row["macd"] < row["macd_signal"]

    if macd_bull:
        score += 15
    elif macd_bear:
        score -= 15

    if row["macd"] > row["macd_signal"] and prev["macd"] <= prev["macd_signal"]:
        score += 10
    elif row["macd"] < row["macd_signal"] and prev["macd"] >= prev["macd_signal"]:
        score -= 10

    if (
        score >= 60
        and bullish_trend
        and row["close"] >= row["ema20"]
        and 45 <= row["rsi"] <= 75
    ):
        signal = "BUY"
    elif (
        score <= -60
        and bearish_trend
        and row["close"] <= row["ema20"]
        and 25 <= row["rsi"] <= 55
    ):
        signal = "SELL"
    else:
        signal = "WAIT"

    return int(score), signal


def _empirical_probability(df, current_score, current_signal):
    """
    Estimate probability from historical signals generated by the same rules.

    Outcome = next candle close in the predicted direction.
    This is a simple historical calibration, not a guarantee of future profit.
    """
    if current_signal == "WAIT":
        return 50

    records = []
    # Use closed historical candles only. Leave the newest row out because it
    # may still be forming and has no known future outcome.
    for i in range(1, len(df) - 1):
        row = df.iloc[i]
        prev = df.iloc[i - 1]
        score, signal = _score_row(row, prev)

        if signal not in {"BUY", "SELL"}:
            continue

        next_close = float(df.iloc[i + 1]["close"])
        close_now = float(row["close"])
        won = next_close > close_now if signal == "BUY" else next_close < close_now

        # Compare signals of similar strength, not every historical signal.
        if abs(score - current_score) <= 20 and signal == current_signal:
            records.append(int(won))

    # If the similar-signal sample is too small, broaden the sample.
    if len(records) < 8:
        records = []
        for i in range(1, len(df) - 1):
            row = df.iloc[i]
            prev = df.iloc[i - 1]
            score, signal = _score_row(row, prev)
            if signal != current_signal:
                continue
            next_close = float(df.iloc[i + 1]["close"])
            close_now = float(row["close"])
            won = next_close > close_now if signal == "BUY" else next_close < close_now
            records.append(int(won))

    if len(records) >= 8:
        # Light smoothing avoids presenting 100%/0% from a small sample.
        wins = sum(records)
        n = len(records)
        probability = round((wins + 1) / (n + 2) * 100)
        return max(50, min(90, probability))

    # Not enough historical signals: use a conservative confidence estimate.
    # This is explicitly a fallback, not a historical win rate.
    fallback = 50 + min(30, max(0, abs(current_score) - 60))
    return int(fallback)


def analyze(symbol="BTCUSDT", interval="1h"):
    candles, error = _get_candles(symbol, interval)
    if error:
        return error

    df = _indicator_frame(candles)
    if len(df) < 3:
        return {"error": "Not enough data after indicator calculation"}

    last = df.iloc[-1]
    prev = df.iloc[-2]

    score, signal = _score_row(last, prev)

    if last["ema20"] > last["ema50"] > last["ema200"]:
        trend = "UPTREND"
    elif last["ema20"] < last["ema50"] < last["ema200"]:
        trend = "DOWNTREND"
    else:
        trend = "SIDEWAYS"

    # Calibrate against closed historical candles. The current candle remains
    # live, so ENTRY NOW can appear without waiting for candle close.
    probability = _empirical_probability(df, score, signal)

    entry = "NOW" if signal in {"BUY", "SELL"} else None
    trade_time = "NOW" if signal in {"BUY", "SELL"} else None

    return {
        "signal": signal,
        "trend": trend,
        "score": int(score),
        "probability": int(probability),
        "entry": entry,
        "entry_now": signal in {"BUY", "SELL"},
        "trade_time": trade_time,
        "signal_live": True,
        "price": round(float(last["close"]), 8),
        "ema20": round(float(last["ema20"]), 8),
        "ema50": round(float(last["ema50"]), 8),
        "ema200": round(float(last["ema200"]), 8),
        "rsi": round(float(last["rsi"]), 2),
        "macd": round(float(last["macd"]), 8),
        "macd_signal": round(float(last["macd_signal"]), 8),
        "atr": round(float(last["atr"]), 8),
        "interval": interval,
        "symbol": symbol.upper(),
        "source": "OKX",
    }
